logging:
  level:
    org.jooq: info

---
spring:
  flyway:
    create-schemas: true
    schemas:
      - cinema
  jooq:
    sql-dialect: h2

---
graphql:
  tools:
    schema-location-pattern: io/github/ermadmi78/kobby/cinema/api/cinema.graphqls

---
voyager:
  enabled: true
  cdn:
    enabled: true

---
graphiql:
  enabled: true
  cdn:
    enabled: true